### ISSUE TITLE
Wrong constant picked during deserialization

### ISSUE THREAD

**Issue by jackric** [adamboche/python-marshmallow-union#30] opened 2020-01-28 15:49 UTC
Preface: apologies for the light report; I want to capture this problem and come back later with more detail.

I'm using webargs and marshmallow_union, and it's deserializing the input into the wrong `Const`.

```python
args = {
    "foo":
        marshmallow_union.Union(
            [
                fields.Nested(
                    {
                        "key": fields.Str(required=True),
                    }
                ),
                fields.Constant("spam"),
                fields.Constant("spinach"),
            ]
        )
    ),
}
```
Feeding the JSON input:
```
{"foo": [{"key": "blah blah"}, "spinach"]}
```
It's getting parsed as:
```
{"foo": [{"key": "blah blah"}, "spam"]}
```

Versions are all latest at time of writing:
```
webargs==5.5.2
marshmallow==3.3.0
marshmallow-union==0.1.12
```

**Comment by YBadiss** [comment] 2020-01-30 14:50
@adamboche do `marshmallow_union.Union` even work with Nested fields?

**Comment by adamboche** [comment] 2020-01-30 20:20
@YBadiss 

> do marshmallow_union.Union even work with Nested fields?

I think so. For example,

```py
import marshmallow
from marshmallow import fields
import marshmallow_union


class SchemaA(marshmallow.Schema):
    x = fields.Int()


class MySchema(marshmallow.Schema):
    foo = fields.List(
        marshmallow_union.Union([fields.Nested(SchemaA()), fields.Float()])
    )


data = {"foo": [{"x": 5}, 4.2]}
parsed = MySchema().load(data)
assert parsed == {"foo": [{"x": 5}, 4.2]}
```

**Comment by adamboche** [comment] 2020-01-30 20:33
@jackric 

I think the issue you're experiencing is that [`marshmallow.fields.Constant(x)`](https://marshmallow.readthedocs.io/en/stable/_modules/marshmallow/fields.html#Constant) does not verify that the deserialized value matches the expected constant `x`. For example,

```py
>>> from marshmallow import fields
>>> fields.Constant('foo').deserialize('bar')
'foo'
```

Since the deserialization succeeds without error, `marshmallow_union` thinks it landed on the right field.

This seems like unexpected behavior, and evidently has [surprised others too](https://github.com/marshmallow-code/marshmallow/issues/1175), so it might be worth asking Marshmallow to reconsider that behavior or at least provide a warning in the `fields.Constant` documentation.

To get the behavior you wanted, you can use `fields.String(validate=fields.validate.Equal())`, like this:

```py
import marshmallow
from marshmallow import fields
import marshmallow_union


class SchemaA(marshmallow.Schema):
    x = fields.Int()


class MySchema(marshmallow.Schema):
    foo = fields.List(
        marshmallow_union.Union(
            [
                fields.Nested(SchemaA()),
                fields.String(validate=fields.validate.Equal("spam")),
                fields.String(validate=fields.validate.Equal("eggs")),
            ]
        )
    )


data = {"foo": [{"x": 5}, "spam", "eggs", {"x": 4}, "spam"]}
parsed = MySchema().load(data)
print(parsed) # {'foo': [{'x': 5}, 'spam', 'eggs', {'x': 4}, 'spam']}


```

**Closed as completed** 2020-02-02 00:18 UTC
